git rm --cached

git rm --cached .vs/BlazorMovies/DesignTimeBuild/.dtbcache
git rm --cached .vs/BlazorMovies/config/applicationhost.config
git rm --cached .vs/BlazorMovies/v16/.suo
git rm --cached .vs/BlazorMovies/v16/Server/sqlite3/storage.ide
git rm --cached Client/bin/Debug/netstandard2.1/BlazorMovies.Client.blazor.config
git rm --cached Client/bin/Debug/netstandard2.1/BlazorMovies.Client.dll
git rm --cached Client/bin/Debug/netstandard2.1/BlazorMovies.Client.pdb
git rm --cached Client/bin/Debug/netstandard2.1/BlazorMovies.Shared.dll
git rm --cached Client/bin/Debug/netstandard2.1/BlazorMovies.Shared.pdb
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/BlazorMovies.Client.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/BlazorMovies.Client.pdb
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/BlazorMovies.Shared.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/BlazorMovies.Shared.pdb
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.AspNetCore.Blazor.HttpClient.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.AspNetCore.Blazor.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.AspNetCore.Components.Web.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.AspNetCore.Components.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.Extensions.Configuration.Abstractions.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.Extensions.Configuration.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.Extensions.DependencyInjection.Abstractions.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.Extensions.DependencyInjection.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.Extensions.Logging.Abstractions.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/Microsoft.Extensions.Primitives.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/System.Core.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/System.Net.Http.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/System.Runtime.CompilerServices.Unsafe.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/System.Text.Encodings.Web.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/System.Text.Json.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/System.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/WebAssembly.Bindings.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/WebAssembly.Net.Http.dll
git rm --cached Client/bin/Debug/netstandard2.1/dist/_framework/_bin/mscorlib.dll
git rm --cached Client/obj/BlazorMovies.Client.csproj.nuget.cache
git rm --cached Client/obj/BlazorMovies.Client.csproj.nuget.dgspec.json
git rm --cached Client/obj/BlazorMovies.Client.csproj.nuget.g.props
git rm --cached Client/obj/Debug/netstandard2.1/BlazorMovies.Client.RazorComponent.input.cache
git rm --cached Client/obj/Debug/netstandard2.1/BlazorMovies.Client.RazorCoreGenerate.cache
git rm --cached Client/obj/Debug/netstandard2.1/BlazorMovies.Client.TagHelpers.output.cache
git rm --cached Client/obj/Debug/netstandard2.1/BlazorMovies.Client.assets.cache
git rm --cached Client/obj/Debug/netstandard2.1/BlazorMovies.Client.csproj.FileListAbsolute.txt
git rm --cached Client/obj/Debug/netstandard2.1/BlazorMovies.Client.csprojAssemblyReference.cache
git rm --cached Client/obj/Debug/netstandard2.1/BlazorMovies.Client.dll
git rm --cached Client/obj/Debug/netstandard2.1/BlazorMovies.Client.pdb
git rm --cached Client/obj/Debug/netstandard2.1/Razor/App.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/Pages/Counter.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/Pages/FetchData.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/Pages/Index.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/Shared/IndiviualMovie.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/Shared/MainLayout.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/Shared/MovieList.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/Shared/NavMenu.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/Shared/SurveyPrompt.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/Razor/_Imports.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/App.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/BlazorMovies.Client.dll
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/BlazorMovies.Client.pdb
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/Pages/Counter.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/Pages/FetchData.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/Pages/Index.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/Shared/IndiviualMovie.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/Shared/MainLayout.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/Shared/MovieList.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/Shared/NavMenu.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/Shared/SurveyPrompt.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/RazorDeclaration/_Imports.razor.g.cs
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/BlazorMovies.Client.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/BlazorMovies.Client.pdb
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/BlazorMovies.Shared.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/BlazorMovies.Shared.pdb
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.AspNetCore.Blazor.HttpClient.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.AspNetCore.Blazor.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.AspNetCore.Components.Web.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.AspNetCore.Components.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.Extensions.Configuration.Abstractions.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.Extensions.Configuration.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.Extensions.DependencyInjection.Abstractions.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.Extensions.DependencyInjection.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.Extensions.Logging.Abstractions.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/Microsoft.Extensions.Primitives.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/System.Core.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/System.Net.Http.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/System.Runtime.CompilerServices.Unsafe.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/System.Text.Encodings.Web.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/System.Text.Json.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/System.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/WebAssembly.Bindings.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/WebAssembly.Net.Http.dll
git rm --cached Client/obj/Debug/netstandard2.1/blazor/linker/mscorlib.dll
git rm --cached Client/obj/project.assets.json
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Client.blazor.config
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Client.dll
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Client.pdb
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Server.deps.json
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Server.dll
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Server.exe
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Server.pdb
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Server.runtimeconfig.dev.json
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Shared.dll
git rm --cached Server/bin/Debug/netcoreapp3.1/BlazorMovies.Shared.pdb
git rm --cached Server/bin/Debug/netcoreapp3.1/Properties/launchSettings.json
git rm --cached Server/obj/BlazorMovies.Server.csproj.nuget.cache
git rm --cached Server/obj/BlazorMovies.Server.csproj.nuget.dgspec.json
git rm --cached Server/obj/BlazorMovies.Server.csproj.nuget.g.props
git rm --cached Server/obj/Debug/netcoreapp3.1/BlazorMovies.Server.assets.cache
git rm --cached Server/obj/Debug/netcoreapp3.1/BlazorMovies.Server.csproj.FileListAbsolute.txt
git rm --cached Server/obj/Debug/netcoreapp3.1/BlazorMovies.Server.csprojAssemblyReference.cache
git rm --cached Server/obj/Debug/netcoreapp3.1/BlazorMovies.Server.dll
git rm --cached Server/obj/Debug/netcoreapp3.1/BlazorMovies.Server.exe
git rm --cached Server/obj/Debug/netcoreapp3.1/BlazorMovies.Server.pdb
git rm --cached Server/obj/project.assets.json
git rm --cached Shared/bin/Debug/netstandard2.1/BlazorMovies.Shared.dll
git rm --cached Shared/bin/Debug/netstandard2.1/BlazorMovies.Shared.pdb
git rm --cached Shared/obj/BlazorMovies.Shared.csproj.nuget.cache
git rm --cached Shared/obj/BlazorMovies.Shared.csproj.nuget.dgspec.json
git rm --cached Shared/obj/BlazorMovies.Shared.csproj.nuget.g.props
git rm --cached Shared/obj/Debug/netstandard2.1/BlazorMovies.Shared.assets.cache
git rm --cached Shared/obj/Debug/netstandard2.1/BlazorMovies.Shared.csproj.FileListAbsolute.txt
git rm --cached Shared/obj/Debug/netstandard2.1/BlazorMovies.Shared.dll
git rm --cached Shared/obj/Debug/netstandard2.1/BlazorMovies.Shared.pdb
git rm --cached Shared/obj/project.assets.json
